### ISSUE TITLE
Add and Remove Buttons Not Working

### ISSUE THREAD

**Issue by DipeshSt** [Collaborative-Develoment-GroupA/traffic-management#4]
Users are unable to add or remove items from a list or edit a form because the Add and Remove buttons on the website are not functional or don't work as intended.

**Comment by Nancy740** [comment]
![image](https://github.com/Collaborative-Develoment-GroupA/traffic-management/assets/127962570/d2144632-54fd-427d-aaf6-f410986e8d45)
![image](https://github.com/Collaborative-Develoment-GroupA/traffic-management/assets/127962570/e4fc7177-6810-42cd-a85a-5e24c304eeb6)
