### ISSUE TITLE
Change in the background 

### ISSUE THREAD

**Issue by DipeshSt** [Collaborative-Develoment-GroupA/traffic-management#7]
The background of the webpage needs to be changed as it doesn't match the color theme of our project.

**Comment by Nancy740** [comment]
![image](https://github.com/Collaborative-Develoment-GroupA/traffic-management/assets/127962570/8fb9799e-eb68-4be8-80ef-aa408879289c)
changed

**Comment by Nancy740** [comment]
![image](https://github.com/Collaborative-Develoment-GroupA/traffic-management/assets/127962570/fe58690d-f2ca-4288-be8d-cddbea7745b0)
